### ISSUE TITLE
Question about JANUS

### ISSUE THREAD

**Issue by Nonomeme** [kirkedal/rfun#1]
Hi,
    Sorry for leaving a message here... actually it's not an issue... I just got some question to ask about janus but have no idea how to contact. So...
    Well, I'm now working on reversible algorithms based on janus, I know there is an online interpreter, but I want to make it run on personal computer. I accidentally got news that there is interpreter code of Janus in your git repository, but I only find rfun. Could you share it again?

Best regards.

**Comment by kirkedal** [comment]
Hi Nanomeme,

I have granted you access to it. The Janus interpreter is a mix of different tools and code bases, but the interpreter itself is quite stabel. I have had a longstanding plan to update it and make it public, but the time for this has been limited. If you have problems, you can write to me.

There is also an installation on a virtual machine, if you prefer this. It also contains other tools, so it is quite sizeable. You can read more about it here:
https://github.com/COST-IC1405/tr_materials/tree/master/VM%20(with%20tools)%20setup
